### PR TITLE
Add support for UWP resw files

### PR DESCRIPTION
**Pull request by hampoelz**

### CODE REVIEW

**Comment by htcfreek** [comment]
@DominicVonk 
Are there any plans to support/merge and release this?

**Comment by DominicVonk** [comment]
I will merge this tomorrow, and I will apply some bug fixes

**Comment by htcfreek** [comment]
> I will merge this tomorrow, and I will apply some bug fixes

cc: @jay-o-way

**Comment by Jay-o-Way** [comment]
Any idea when the plug-in is updated?

**Comment by Jay-o-Way** [comment]
@DominicVonk I still don't see this updated in VS Code up to today. When can we expect an update?
Changelog is pretty empty too.

**Pull request merged**
